In [116]:
import pandas as pd
a= pd.read_csv('환경부 크롤링1628817861')
b= pd.read_csv('환경부 크롤링1628821497')
c= pd.read_csv('환경부 크롤링1628825833')
d= pd.read_csv('환경부 크롤링1628830950')
e= pd.read_csv('환경부 크롤링1628835759')
f= pd.read_csv('환경부 크롤링1628839934')
g=pd.read_csv('환경부 크롤링1628843966')
h=pd.read_csv('환경부 크롤링1628846947')
i=pd.read_csv('환경부 크롤링1628850675')
j=pd.read_csv('환경부 크롤링1628854017')
k=pd.read_csv('환경부 크롤링1628856787')
l=pd.read_csv('환경부 크롤링1628860506')
m=pd.read_csv('환경부 크롤링1628867002')

In [117]:
x=pd.read_excel('data/유선부분_동.xlsx')
x=x[['동']]
x.head()
len(x)

67

In [118]:
y=pd.read_excel('data/승현.xlsx')
y=y[['동']]
y.head()
len(y)

138

In [119]:
xy=pd.concat([y,x],ignore_index=True)
xy

       동
0    개포동
1    삼성동
2    개포동
3    일원동
4    일원동
..   ...
200  중화동
201  면목동
202  상봉동
203  신내동
204  신내동

[205 rows x 1 columns]

In [107]:
# a=a[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# a['동']=xy['동']
# a.head()

    구명  시설분류                주차장명  사용상태 충전기타입                        수집시간    동
0  강남구  공공시설          sh서울주택도시공사  사용가능    급속  2021-08-13 10:13:28.118352  개포동
1  강남구  공공시설  강남구청 삼성로 별관 부설 주차장   사용중    급속  2021-08-13 10:13:28.118352  삼성동
2  강남구  공공시설           일원2동 주민센터  사용가능    급속  2021-08-13 10:13:28.118352  개포동
3  강남구  공공시설           일원본동 주민센터   사용중    급속  2021-08-13 10:13:28.118352  일원동
4  강남구  공공시설             탄천물재생센터  사용가능    급속  2021-08-13 10:13:28.118352  일원동

In [120]:
df_list=[a,b,c,d,e,f,g,h,i,j,k,l,m]
dfs=[]
for x in df_list:
    x=x[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
    x['동']=xy['동']
    dfs.append(x)

In [121]:
result=pd.DataFrame(columns=(['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']))
result=pd.concat([dfs[0],dfs[1],dfs[2],dfs[3],dfs[4],dfs[5],dfs[6],dfs[7],dfs[8],dfs[9],dfs[10],dfs[11],dfs[12]],ignore_index=True)
result.head()

    구명  시설분류                주차장명  사용상태 충전기타입                        수집시간    동
0  강남구  공공시설          sh서울주택도시공사  사용가능    급속  2021-08-13 10:13:28.118352  개포동
1  강남구  공공시설  강남구청 삼성로 별관 부설 주차장   사용중    급속  2021-08-13 10:13:28.118352  삼성동
2  강남구  공공시설           일원2동 주민센터  사용가능    급속  2021-08-13 10:13:28.118352  개포동
3  강남구  공공시설           일원본동 주민센터   사용중    급속  2021-08-13 10:13:28.118352  일원동
4  강남구  공공시설             탄천물재생센터  사용가능    급속  2021-08-13 10:13:28.118352  일원동

In [59]:
# a=a[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# a['동']=xy['동']
# b=b[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# b['동']=xy['동']
# c=c[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# c['동']=xy['동']
# d=d[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# d['동']=xy['동']
# e=e[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# e['동']=xy['동']
# f=f[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# f['동']=xy['동']
# g=g[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# g['동']=xy['동']
# h=h[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# h['동']=xy['동']
# i=i[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# i['동']=xy['동']
# j=j[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# j['동']=xy['동']
# k=k[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# k['동']=xy['동']
# l=l[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# l['동']=xy['동']
# m=m[['구명','시설분류','주차장명','사용상태','충전기타입','수집시간']]
# m['동']=xy['동']

In [122]:
result=result.sort_values(by=['구명','주차장명','수집시간'],ascending=[True,True,True])
result=result.reset_index(drop=True)
result.head()

    구명  시설분류   주차장명  사용상태 충전기타입                        수집시간    동
0  강남구  관광시설  SETEC  사용가능    급속  2021-08-13 10:13:38.885080  대치동
1  강남구  관광시설  SETEC  사용가능    급속  2021-08-13 11:13:45.572375  대치동
2  강남구  관광시설  SETEC  사용가능    급속  2021-08-13 12:27:41.521462  대치동
3  강남구  관광시설  SETEC  사용가능    급속  2021-08-13 13:52:57.470021  대치동
4  강남구  관광시설  SETEC  사용가능    급속  2021-08-13 15:13:02.771739  대치동

In [123]:
result.to_csv('210813 환경부 크롤링.csv',index=False)